### ISSUE TITLE
Update for app delegate adaptor

### ISSUE THREAD

**Issue by malhal** [vmanot/SwiftDB#3]
If you use UIApplicationDelegateAdaptor then you don't need to wrap a NSPersistentContainer in an ObservableObject and you can save on applicationDidEnterBackground and in an App struct you can set delegate.persistentContainer.viewContext on the Environment. You could subclass NSPersistentContainer/NSPersistentCloudKitContainer (which is what it is designed for) and that would still allow loading other stores for additional model configurations, which is essential for CloudKit containers.

**Comment by vmanot** [comment]
@malhal thank you for raising the issue! `UIApplicationDelegateAdaptor` will not help here because with/without it there is no direct access to the `Environment` of the underlying `UIHostingController`. The typical boilerplate that sets up `persistentContainer` on the `AppDelegate` is just that - boilerplate. There's no delegate property on `UIApplicationDelegate` that exposes an `NSPersistentContainer` - so it really doesn't matter where it's stored :)

**Comment by vmanot** [comment]
Closing this issue, please feel free to reopen it if you have any further concerns.

**Comment by malhal** [comment]
Give this a try:

```
import SwiftUI
import CoreData

@main
struct MasterDetailApp: App {
    
    @UIApplicationDelegateAdaptor var appDelegate : AppDelegate
    
    var body: some Scene {
        WindowGroup {
            ContentView().environment(\.managedObjectContext, appDelegate.persistentContainer.viewContext)
        }
    }
    
}
```

The persistentContainer needs to be in the app delegate so the context can be saved when the app suspends.

**Comment by vmanot** [comment]
@malhal the `AppDelegate` is not a part of the `SwiftUI` or `UIKit` module. There is no way for me to reference it within SwiftDB.
